/settings/text/snippets:
  get:
    tags:
    - Text Snippets
    summary: Return all text snippets
    operationId: listText_snippets
    description: Outlines the parameters, optional and required, used when requesting
      the data for all TextSnippets
    parameters:
    - $ref: '#/components/parameters/X-API-VERSION'
    - $ref: '#/components/parameters/created_since'
    - $ref: '#/components/parameters/fields'
    - $ref: ./components/parameters/ids[].yaml
    - $ref: '#/components/parameters/limit'
    - $ref: '#/components/parameters/order'
    - $ref: '#/components/parameters/page_token'
    - $ref: '#/components/parameters/query'
    - $ref: '#/components/parameters/updated_since'
    responses:
      '200':
        $ref: '#/components/responses/200_Ok'
      '400':
        $ref: '#/components/responses/400_Bad_Request'
      '401':
        $ref: '#/components/responses/401_Unauthorized'
      '403':
        $ref: '#/components/responses/403_Forbidden'
      '429':
        $ref: '#/components/responses/429_Too_Many_Requests'
  post:
    tags:
    - Text Snippets
    summary: Create a text snippet
    operationId: createText_snippet
    description: Outlines the parameters and data fields used when creating a new
      TextSnippet
    parameters:
    - $ref: '#/components/parameters/X-API-VERSION'
    - $ref: '#/components/parameters/fields'
    responses:
      '201':
        $ref: '#/components/responses/201_Created'
      '400':
        $ref: '#/components/responses/400_Bad_Request'
      '401':
        $ref: '#/components/responses/401_Unauthorized'
      '403':
        $ref: '#/components/responses/403_Forbidden'
      '404':
        $ref: '#/components/responses/404_Not_Found'
      '422':
        $ref: '#/components/responses/422_Unprocessable_Entity'
      '429':
        $ref: '#/components/responses/429_Too_Many_Requests'
    requestBody:
      $ref: '#/components/requestBodies/ReqBody_5ba486b3'
