from typing import Optional

from pydantic import BaseModel


class ContactBaseIn(BaseModel):
    id: Optional[int] = None
    etag: Optional[str] = None
    name: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    last_name: Optional[str] = None
    date_of_birth: Optional[str] = None
    type: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    prefix: Optional[str] = None
    title: Optional[str] = None
    initials: Optional[str] = None
    clio_connect_email: Optional[str] = None
    locked_clio_connect_email: Optional[bool] = None
    client_connect_user_id: Optional[int] = None
    primary_email_address: Optional[str] = None
    secondary_email_address: Optional[str] = None
    primary_phone_number: Optional[str] = None
    secondary_phone_number: Optional[str] = None
    ledes_client_id: Optional[str] = None
    has_clio_for_clients_permission: Optional[bool] = None
    is_client: Optional[bool] = None
    is_clio_for_client_user: Optional[bool] = None
    is_co_counsel: Optional[bool] = None
    is_bill_recipient: Optional[bool] = None
    sales_tax_number: Optional[str] = None

class ContactBaseOut(BaseModel):
    id: Optional[int] = None
    etag: Optional[str] = None
    name: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    last_name: Optional[str] = None
    date_of_birth: Optional[str] = None
    type: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    prefix: Optional[str] = None
    title: Optional[str] = None
    initials: Optional[str] = None
    clio_connect_email: Optional[str] = None
    locked_clio_connect_email: Optional[bool] = None
    client_connect_user_id: Optional[int] = None
    primary_email_address: Optional[str] = None
    secondary_email_address: Optional[str] = None
    primary_phone_number: Optional[str] = None
    secondary_phone_number: Optional[str] = None
    ledes_client_id: Optional[str] = None
    has_clio_for_clients_permission: Optional[bool] = None
    is_client: Optional[bool] = None
    is_clio_for_client_user: Optional[bool] = None
    is_co_counsel: Optional[bool] = None
    is_bill_recipient: Optional[bool] = None
    sales_tax_number: Optional[str] = None

class ContactBaseUpdate(BaseModel):
    id: Optional[int] = None
    etag: Optional[str] = None
    name: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    last_name: Optional[str] = None
    date_of_birth: Optional[str] = None
    type: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    prefix: Optional[str] = None
    title: Optional[str] = None
    initials: Optional[str] = None
    clio_connect_email: Optional[str] = None
    locked_clio_connect_email: Optional[bool] = None
    client_connect_user_id: Optional[int] = None
    primary_email_address: Optional[str] = None
    secondary_email_address: Optional[str] = None
    primary_phone_number: Optional[str] = None
    secondary_phone_number: Optional[str] = None
    ledes_client_id: Optional[str] = None
    has_clio_for_clients_permission: Optional[bool] = None
    is_client: Optional[bool] = None
    is_clio_for_client_user: Optional[bool] = None
    is_co_counsel: Optional[bool] = None
    is_bill_recipient: Optional[bool] = None
    sales_tax_number: Optional[str] = None

class ContactBaseDb(BaseModel):
    id: Optional[int] = None
    etag: Optional[str] = None
    name: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    last_name: Optional[str] = None
    date_of_birth: Optional[str] = None
    type: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    prefix: Optional[str] = None
    title: Optional[str] = None
    initials: Optional[str] = None
    clio_connect_email: Optional[str] = None
    locked_clio_connect_email: Optional[bool] = None
    client_connect_user_id: Optional[int] = None
    primary_email_address: Optional[str] = None
    secondary_email_address: Optional[str] = None
    primary_phone_number: Optional[str] = None
    secondary_phone_number: Optional[str] = None
    ledes_client_id: Optional[str] = None
    has_clio_for_clients_permission: Optional[bool] = None
    is_client: Optional[bool] = None
    is_clio_for_client_user: Optional[bool] = None
    is_co_counsel: Optional[bool] = None
    is_bill_recipient: Optional[bool] = None
    sales_tax_number: Optional[str] = None

