"""
This file defines the `Task` model used in the Clio SDK layer.

It serves as a simplified and ergonomic Pydantic model that aggregates relevant fields from
multiple low-level models generated by the clio_client (e.g., task_base.py, task_show.py, task_assignee.py).

This model is designed for internal use across the SDK's queries, commands, and adapters,
providing a clean, consistent interface for task-related data.

Copilot Prompt:
- Aggregate fields from multiple clio_client models into a single SDK-level Pydantic model.
- Include only the fields that are relevant for typical application usage (e.g., due_date, matter_id, assignee_id).
- Keep fields optional unless business logic requires them to be mandatory.
- The goal is to hide the complexity of the clio_client's highly normalized models.
"""


from datetime import date
from typing import Optional

from pydantic import BaseModel


class Task(BaseModel):
    id: Optional[int]
    description: Optional[str]
    status: Optional[str]
    priority: Optional[str]
    due_date: Optional[date]
    matter_id: Optional[int]
    assignee_id: Optional[int]
    created_by: Optional[int]
