# Adapter stubs for PolymorphiccustomrateActivitydescriptionBase
from schemas.from_expanded.polymorphiccustomrateactivitydescriptionbase import PolymorphiccustomrateActivitydescriptionBaseIn, PolymorphiccustomrateActivitydescriptionBaseOut, PolymorphiccustomrateActivitydescriptionBaseUpdate, PolymorphiccustomrateActivitydescriptionBaseDb

def convert_sdk_to_polymorphiccustomrateactivitydescriptionbaseout(sdk_obj):
    # TODO
    return PolymorphiccustomrateActivitydescriptionBaseOut()

def convert_polymorphiccustomrateactivitydescriptionbasein_to_sdk(model):
    # TODO
    return None
