# Adapter for polymorphiccustomrateactivitydescriptionbase
from clio_sdk.models.polymorphiccustomrateactivitydescriptionbase import PolymorphiccustomrateactivitydescriptionbaseIn, PolymorphiccustomrateactivitydescriptionbaseOut, PolymorphiccustomrateactivitydescriptionbaseUpdate, PolymorphiccustomrateactivitydescriptionbaseDb
from clio_client.models import polymorphic_custom_rate_activity_description_base

def convert_sdk_to_polymorphiccustomrateactivitydescriptionbaseout(src: polymorphic_custom_rate_activity_description_base) -> PolymorphiccustomrateactivitydescriptionbaseOut:
    return PolymorphiccustomrateactivitydescriptionbaseOut(**src.dict())

def convert_polymorphiccustomrateactivitydescriptionbasein_to_sdk(src: PolymorphiccustomrateactivitydescriptionbaseIn) -> polymorphic_custom_rate_activity_description_base:
    return polymorphic_custom_rate_activity_description_base(**src.dict())
