# Adapter stubs for Medicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinner
from schemas.from_spec.medicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinner import MedicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerIn, MedicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerOut, MedicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerUpdate, MedicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerDb

def convert_sdk_to_medicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerout(sdk_obj):
    # TODO
    return MedicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerOut()

def convert_medicalrecordsrequestupdaterequestdatamedicalbillsinnerpayersinnerin_to_sdk(model):
    # TODO
    return None
