# Adapter stubs for Communicationupdaterequestdatanotificationeventsubscribersinner
from schemas.from_spec.communicationupdaterequestdatanotificationeventsubscribersinner import CommunicationupdaterequestdatanotificationeventsubscribersinnerIn, CommunicationupdaterequestdatanotificationeventsubscribersinnerOut, CommunicationupdaterequestdatanotificationeventsubscribersinnerUpdate, CommunicationupdaterequestdatanotificationeventsubscribersinnerDb

def convert_sdk_to_communicationupdaterequestdatanotificationeventsubscribersinnerout(sdk_obj):
    # TODO
    return CommunicationupdaterequestdatanotificationeventsubscribersinnerOut()

def convert_communicationupdaterequestdatanotificationeventsubscribersinnerin_to_sdk(model):
    # TODO
    return None
