# Adapter stubs for Polymorphiccustomrateactivitydescriptionbase
from schemas.from_spec.polymorphiccustomrateactivitydescriptionbase import PolymorphiccustomrateactivitydescriptionBaseIn, PolymorphiccustomrateactivitydescriptionBaseOut, PolymorphiccustomrateactivitydescriptionBaseUpdate, PolymorphiccustomrateactivitydescriptionBaseDb

def convert_sdk_to_polymorphiccustomrateactivitydescriptionBaseOut(sdk_obj):
    # TODO
    return PolymorphiccustomrateactivitydescriptionBaseOut()

def convert_polymorphiccustomrateactivitydescriptionBaseIn_to_sdk(model):
    # TODO
    return None
