# Adapter stubs for Medicalrecordsrequestupdaterequestdatamedicalrecordsinner
from schemas.from_spec.medicalrecordsrequestupdaterequestdatamedicalrecordsinner import MedicalrecordsrequestupdaterequestdatamedicalrecordsinnerIn, MedicalrecordsrequestupdaterequestdatamedicalrecordsinnerOut, MedicalrecordsrequestupdaterequestdatamedicalrecordsinnerUpdate, MedicalrecordsrequestupdaterequestdatamedicalrecordsinnerDb

def convert_sdk_to_medicalrecordsrequestupdaterequestdatamedicalrecordsinnerout(sdk_obj):
    # TODO
    return MedicalrecordsrequestupdaterequestdatamedicalrecordsinnerOut()

def convert_medicalrecordsrequestupdaterequestdatamedicalrecordsinnerin_to_sdk(model):
    # TODO
    return None
