# Adapter stubs for Notecreaterequestdatanotificationeventsubscribersinner
from schemas.from_spec.notecreaterequestdatanotificationeventsubscribersinner import NotecreaterequestdatanotificationeventsubscribersinnerIn, NotecreaterequestdatanotificationeventsubscribersinnerOut, NotecreaterequestdatanotificationeventsubscribersinnerUpdate, NotecreaterequestdatanotificationeventsubscribersinnerDb

def convert_sdk_to_notecreaterequestdatanotificationeventsubscribersinnerout(sdk_obj):
    # TODO
    return NotecreaterequestdatanotificationeventsubscribersinnerOut()

def convert_notecreaterequestdatanotificationeventsubscribersinnerin_to_sdk(model):
    # TODO
    return None
