# Adapter stubs for Contactupdaterequestdataemailaddressesinner
from schemas.from_spec.contactupdaterequestdataemailaddressesinner import ContactupdaterequestdataemailaddressesinnerIn, ContactupdaterequestdataemailaddressesinnerOut, ContactupdaterequestdataemailaddressesinnerUpdate, ContactupdaterequestdataemailaddressesinnerDb

def convert_sdk_to_contactupdaterequestdataemailaddressesinnerout(sdk_obj):
    # TODO
    return ContactupdaterequestdataemailaddressesinnerOut()

def convert_contactupdaterequestdataemailaddressesinnerin_to_sdk(model):
    # TODO
    return None
