# Adapter stubs for Folderupdaterequestdataexternalpropertiesinner
from schemas.from_spec.folderupdaterequestdataexternalpropertiesinner import FolderupdaterequestdataexternalpropertiesinnerIn, FolderupdaterequestdataexternalpropertiesinnerOut, FolderupdaterequestdataexternalpropertiesinnerUpdate, FolderupdaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_folderupdaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return FolderupdaterequestdataexternalpropertiesinnerOut()

def convert_folderupdaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
