# Adapter stubs for Tasktemplatelistcreaterequestdatapracticearea
from schemas.from_spec.tasktemplatelistcreaterequestdatapracticearea import TasktemplatelistcreaterequestdatapracticeareaIn, TasktemplatelistcreaterequestdatapracticeareaOut, TasktemplatelistcreaterequestdatapracticeareaUpdate, TasktemplatelistcreaterequestdatapracticeareaDb

def convert_sdk_to_tasktemplatelistcreaterequestdatapracticeareaout(sdk_obj):
    # TODO
    return TasktemplatelistcreaterequestdatapracticeareaOut()

def convert_tasktemplatelistcreaterequestdatapracticeareain_to_sdk(model):
    # TODO
    return None
