# Adapter stubs for Contactcreaterequestdatacustomfieldsetassociationsinnercustomfieldset
from schemas.from_spec.contactcreaterequestdatacustomfieldsetassociationsinnercustomfieldset import \
    ContactcreaterequestdatacustomfieldsetassociationsinnercustomfieldsetOut


def convert_sdk_to_contactcreaterequestdatacustomfieldsetassociationsinnercustomfieldsetout(sdk_obj):
    # TODO
    return ContactcreaterequestdatacustomfieldsetassociationsinnercustomfieldsetOut()

def convert_contactcreaterequestdatacustomfieldsetassociationsinnercustomfieldsetin_to_sdk(model):
    # TODO
    return None
