# Adapter stubs for Matterupdaterequestdatatasktemplatelistinstancesinnertasktemplatelist
from schemas.from_spec.matterupdaterequestdatatasktemplatelistinstancesinnertasktemplatelist import \
    MatterupdaterequestdatatasktemplatelistinstancesinnertasktemplatelistOut


def convert_sdk_to_matterupdaterequestdatatasktemplatelistinstancesinnertasktemplatelistout(sdk_obj):
    # TODO
    return MatterupdaterequestdatatasktemplatelistinstancesinnertasktemplatelistOut()

def convert_matterupdaterequestdatatasktemplatelistinstancesinnertasktemplatelistin_to_sdk(model):
    # TODO
    return None
