# Adapter stubs for Documentcreaterequestdataexternalpropertiesinner
from schemas.from_spec.documentcreaterequestdataexternalpropertiesinner import DocumentcreaterequestdataexternalpropertiesinnerIn, DocumentcreaterequestdataexternalpropertiesinnerOut, DocumentcreaterequestdataexternalpropertiesinnerUpdate, DocumentcreaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_documentcreaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return DocumentcreaterequestdataexternalpropertiesinnerOut()

def convert_documentcreaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
