# Adapter stubs for Mattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethod
from schemas.from_spec.mattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethod import MattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodIn, MattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodOut, MattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodUpdate, MattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodDb

def convert_sdk_to_mattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodout(sdk_obj):
    # TODO
    return MattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodOut()

def convert_mattercreaterequestdatastatuteoflimitationsremindersinnernotificationmethodin_to_sdk(model):
    # TODO
    return None
