# Adapter stubs for Mattercreaterequestdatasplitinvoicepayersinner
from schemas.from_spec.mattercreaterequestdatasplitinvoicepayersinner import MattercreaterequestdatasplitinvoicepayersinnerIn, MattercreaterequestdatasplitinvoicepayersinnerOut, MattercreaterequestdatasplitinvoicepayersinnerUpdate, MattercreaterequestdatasplitinvoicepayersinnerDb

def convert_sdk_to_mattercreaterequestdatasplitinvoicepayersinnerout(sdk_obj):
    # TODO
    return MattercreaterequestdatasplitinvoicepayersinnerOut()

def convert_mattercreaterequestdatasplitinvoicepayersinnerin_to_sdk(model):
    # TODO
    return None
