# Adapter stubs for Cliopaymentslinkcreaterequestdatadestinationaccount
from schemas.from_spec.cliopaymentslinkcreaterequestdatadestinationaccount import CliopaymentslinkcreaterequestdatadestinationaccountIn, CliopaymentslinkcreaterequestdatadestinationaccountOut, CliopaymentslinkcreaterequestdatadestinationaccountUpdate, CliopaymentslinkcreaterequestdatadestinationaccountDb

def convert_sdk_to_cliopaymentslinkcreaterequestdatadestinationaccountout(sdk_obj):
    # TODO
    return CliopaymentslinkcreaterequestdatadestinationaccountOut()

def convert_cliopaymentslinkcreaterequestdatadestinationaccountin_to_sdk(model):
    # TODO
    return None
