# Adapter stubs for Contactupdaterequestdatacustomfieldvaluesinnercustomfield
from schemas.from_spec.contactupdaterequestdatacustomfieldvaluesinnercustomfield import ContactupdaterequestdatacustomfieldvaluesinnercustomfieldIn, ContactupdaterequestdatacustomfieldvaluesinnercustomfieldOut, ContactupdaterequestdatacustomfieldvaluesinnercustomfieldUpdate, ContactupdaterequestdatacustomfieldvaluesinnercustomfieldDb

def convert_sdk_to_contactupdaterequestdatacustomfieldvaluesinnercustomfieldout(sdk_obj):
    # TODO
    return ContactupdaterequestdatacustomfieldvaluesinnercustomfieldOut()

def convert_contactupdaterequestdatacustomfieldvaluesinnercustomfieldin_to_sdk(model):
    # TODO
    return None
