# Adapter stubs for Conversationmessagecreaterequestdataattachment
from schemas.from_spec.conversationmessagecreaterequestdataattachment import ConversationmessagecreaterequestdataattachmentIn, ConversationmessagecreaterequestdataattachmentOut, ConversationmessagecreaterequestdataattachmentUpdate, ConversationmessagecreaterequestdataattachmentDb

def convert_sdk_to_conversationmessagecreaterequestdataattachmentout(sdk_obj):
    # TODO
    return ConversationmessagecreaterequestdataattachmentOut()

def convert_conversationmessagecreaterequestdataattachmentin_to_sdk(model):
    # TODO
    return None
