# Adapter stubs for Matterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethod
from schemas.from_spec.matterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethod import MatterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodIn, MatterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodOut, MatterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodUpdate, MatterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodDb

def convert_sdk_to_matterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodout(sdk_obj):
    # TODO
    return MatterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodOut()

def convert_matterupdaterequestdatastatuteoflimitationsremindersinnernotificationmethodin_to_sdk(model):
    # TODO
    return None
