# Adapter stubs for Calendarentryupdaterequestdataexternalpropertiesinner
from schemas.from_spec.calendarentryupdaterequestdataexternalpropertiesinner import CalendarentryupdaterequestdataexternalpropertiesinnerIn, CalendarentryupdaterequestdataexternalpropertiesinnerOut, CalendarentryupdaterequestdataexternalpropertiesinnerUpdate, CalendarentryupdaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_calendarentryupdaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return CalendarentryupdaterequestdataexternalpropertiesinnerOut()

def convert_calendarentryupdaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
