# Adapter stubs for Documentcopyrequestdataexternalpropertiesinner
from schemas.from_spec.documentcopyrequestdataexternalpropertiesinner import DocumentcopyrequestdataexternalpropertiesinnerIn, DocumentcopyrequestdataexternalpropertiesinnerOut, DocumentcopyrequestdataexternalpropertiesinnerUpdate, DocumentcopyrequestdataexternalpropertiesinnerDb

def convert_sdk_to_documentcopyrequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return DocumentcopyrequestdataexternalpropertiesinnerOut()

def convert_documentcopyrequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
