# Adapter stubs for Communicationcreaterequestdataexternalpropertiesinner
from schemas.from_spec.communicationcreaterequestdataexternalpropertiesinner import CommunicationcreaterequestdataexternalpropertiesinnerIn, CommunicationcreaterequestdataexternalpropertiesinnerOut, CommunicationcreaterequestdataexternalpropertiesinnerUpdate, CommunicationcreaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_communicationcreaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return CommunicationcreaterequestdataexternalpropertiesinnerOut()

def convert_communicationcreaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
