# Adapter stubs for Matterupdaterequestdatarelationshipsinnercontact
from schemas.from_spec.matterupdaterequestdatarelationshipsinnercontact import MatterupdaterequestdatarelationshipsinnercontactIn, MatterupdaterequestdatarelationshipsinnercontactOut, MatterupdaterequestdatarelationshipsinnercontactUpdate, MatterupdaterequestdatarelationshipsinnercontactDb

def convert_sdk_to_matterupdaterequestdatarelationshipsinnercontactout(sdk_obj):
    # TODO
    return MatterupdaterequestdatarelationshipsinnercontactOut()

def convert_matterupdaterequestdatarelationshipsinnercontactin_to_sdk(model):
    # TODO
    return None
