# Adapter stubs for Cliopaymentslinkcreaterequestdatadestinationcontact
from schemas.from_spec.cliopaymentslinkcreaterequestdatadestinationcontact import CliopaymentslinkcreaterequestdatadestinationcontactIn, CliopaymentslinkcreaterequestdatadestinationcontactOut, CliopaymentslinkcreaterequestdatadestinationcontactUpdate, CliopaymentslinkcreaterequestdatadestinationcontactDb

def convert_sdk_to_cliopaymentslinkcreaterequestdatadestinationcontactout(sdk_obj):
    # TODO
    return CliopaymentslinkcreaterequestdatadestinationcontactOut()

def convert_cliopaymentslinkcreaterequestdatadestinationcontactin_to_sdk(model):
    # TODO
    return None
