# Adapter stubs for Matterupdaterequestdatacustomrateratesinneruser
from schemas.from_spec.matterupdaterequestdatacustomrateratesinneruser import MatterupdaterequestdatacustomrateratesinneruserIn, MatterupdaterequestdatacustomrateratesinneruserOut, MatterupdaterequestdatacustomrateratesinneruserUpdate, MatterupdaterequestdatacustomrateratesinneruserDb

def convert_sdk_to_matterupdaterequestdatacustomrateratesinneruserout(sdk_obj):
    # TODO
    return MatterupdaterequestdatacustomrateratesinneruserOut()

def convert_matterupdaterequestdatacustomrateratesinneruserin_to_sdk(model):
    # TODO
    return None
