# Adapter stubs for Mattercreaterequestdataevergreenretainerrecipientsinner
from schemas.from_spec.mattercreaterequestdataevergreenretainerrecipientsinner import MattercreaterequestdataevergreenretainerrecipientsinnerIn, MattercreaterequestdataevergreenretainerrecipientsinnerOut, MattercreaterequestdataevergreenretainerrecipientsinnerUpdate, MattercreaterequestdataevergreenretainerrecipientsinnerDb

def convert_sdk_to_mattercreaterequestdataevergreenretainerrecipientsinnerout(sdk_obj):
    # TODO
    return MattercreaterequestdataevergreenretainerrecipientsinnerOut()

def convert_mattercreaterequestdataevergreenretainerrecipientsinnerin_to_sdk(model):
    # TODO
    return None
