# Adapter stubs for Tasktemplatecreaterequestdatatasktemplatelist
from schemas.from_spec.tasktemplatecreaterequestdatatasktemplatelist import TasktemplatecreaterequestdatatasktemplateListIn, TasktemplatecreaterequestdatatasktemplatelistOut, TasktemplatecreaterequestdatatasktemplatelistUpdate, TasktemplatecreaterequestdatatasktemplatelistDb

def convert_sdk_to_tasktemplatecreaterequestdatatasktemplatelistout(sdk_obj):
    # TODO
    return TasktemplatecreaterequestdatatasktemplatelistOut()

def convert_tasktemplatecreaterequestdatatasktemplatelistin_to_sdk(model):
    # TODO
    return None
