# Adapter stubs for Tasktemplateupdaterequestdataremindertemplatesinner
from schemas.from_spec.tasktemplateupdaterequestdataremindertemplatesinner import TasktemplateupdaterequestdataremindertemplatesinnerIn, TasktemplateupdaterequestdataremindertemplatesinnerOut, TasktemplateupdaterequestdataremindertemplatesinnerUpdate, TasktemplateupdaterequestdataremindertemplatesinnerDb

def convert_sdk_to_tasktemplateupdaterequestdataremindertemplatesinnerout(sdk_obj):
    # TODO
    return TasktemplateupdaterequestdataremindertemplatesinnerOut()

def convert_tasktemplateupdaterequestdataremindertemplatesinnerin_to_sdk(model):
    # TODO
    return None
