# Adapter stubs for Conversationmessagecreaterequestdataconversation
from schemas.from_spec.conversationmessagecreaterequestdataconversation import ConversationmessagecreaterequestdataconversationIn, ConversationmessagecreaterequestdataconversationOut, ConversationmessagecreaterequestdataconversationUpdate, ConversationmessagecreaterequestdataconversationDb

def convert_sdk_to_conversationmessagecreaterequestdataconversationout(sdk_obj):
    # TODO
    return ConversationmessagecreaterequestdataconversationOut()

def convert_conversationmessagecreaterequestdataconversationin_to_sdk(model):
    # TODO
    return None
