# Adapter stubs for Foldercreaterequestdataexternalpropertiesinner
from schemas.from_spec.foldercreaterequestdataexternalpropertiesinner import FoldercreaterequestdataexternalpropertiesinnerIn, FoldercreaterequestdataexternalpropertiesinnerOut, FoldercreaterequestdataexternalpropertiesinnerUpdate, FoldercreaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_foldercreaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return FoldercreaterequestdataexternalpropertiesinnerOut()

def convert_foldercreaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
