# Adapter stubs for Calendarentrycreaterequestdatacalendarowner
from schemas.from_spec.calendarentrycreaterequestdatacalendarowner import CalendarentrycreaterequestdatacalendarownerIn, CalendarentrycreaterequestdatacalendarownerOut, CalendarentrycreaterequestdatacalendarownerUpdate, CalendarentrycreaterequestdatacalendarownerDb

def convert_sdk_to_calendarentrycreaterequestdatacalendarownerout(sdk_obj):
    # TODO
    return CalendarentrycreaterequestdatacalendarownerOut()

def convert_calendarentrycreaterequestdatacalendarownerin_to_sdk(model):
    # TODO
    return None
