# Adapter stubs for Contactcreaterequestdatainstantmessengersinner
from schemas.from_spec.contactcreaterequestdatainstantmessengersinner import ContactcreaterequestdatainstantmessengersinnerIn, ContactcreaterequestdatainstantmessengersinnerOut, ContactcreaterequestdatainstantmessengersinnerUpdate, ContactcreaterequestdatainstantmessengersinnerDb

def convert_sdk_to_contactcreaterequestdatainstantmessengersinnerout(sdk_obj):
    # TODO
    return ContactcreaterequestdatainstantmessengersinnerOut()

def convert_contactcreaterequestdatainstantmessengersinnerin_to_sdk(model):
    # TODO
    return None
