# Adapter stubs for Medicalrecordsrequestcreaterequestdatamedicalrecordsinner
from schemas.from_spec.medicalrecordsrequestcreaterequestdatamedicalrecordsinner import MedicalrecordsrequestcreaterequestdatamedicalrecordsinnerIn, MedicalrecordsrequestcreaterequestdatamedicalrecordsinnerOut, MedicalrecordsrequestcreaterequestdatamedicalrecordsinnerUpdate, MedicalrecordsrequestcreaterequestdatamedicalrecordsinnerDb

def convert_sdk_to_medicalrecordsrequestcreaterequestdatamedicalrecordsinnerout(sdk_obj):
    # TODO
    return MedicalrecordsrequestcreaterequestdatamedicalrecordsinnerOut()

def convert_medicalrecordsrequestcreaterequestdatamedicalrecordsinnerin_to_sdk(model):
    # TODO
    return None
