# Adapter stubs for Contactcreaterequestdataemailaddressesinner
from schemas.from_spec.contactcreaterequestdataemailaddressesinner import ContactcreaterequestdataemailaddressesinnerIn, ContactcreaterequestdataemailaddressesinnerOut, ContactcreaterequestdataemailaddressesinnerUpdate, ContactcreaterequestdataemailaddressesinnerDb

def convert_sdk_to_contactcreaterequestdataemailaddressesinnerout(sdk_obj):
    # TODO
    return ContactcreaterequestdataemailaddressesinnerOut()

def convert_contactcreaterequestdataemailaddressesinnerin_to_sdk(model):
    # TODO
    return None
