# Adapter stubs for Expensecategorycreaterequestdatagroupsinner
from schemas.from_spec.expensecategorycreaterequestdatagroupsinner import ExpensecategorycreaterequestdatagroupsinnerIn, ExpensecategorycreaterequestdatagroupsinnerOut, ExpensecategorycreaterequestdatagroupsinnerUpdate, ExpensecategorycreaterequestdatagroupsinnerDb

def convert_sdk_to_expensecategorycreaterequestdatagroupsinnerout(sdk_obj):
    # TODO
    return ExpensecategorycreaterequestdatagroupsinnerOut()

def convert_expensecategorycreaterequestdatagroupsinnerin_to_sdk(model):
    # TODO
    return None
