# Adapter stubs for Tasktemplatelistcopyrequestdatapracticearea
from schemas.from_spec.tasktemplatelistcopyrequestdatapracticearea import TasktemplatelistcopyrequestdatapracticeareaIn, TasktemplatelistcopyrequestdatapracticeareaOut, TasktemplatelistcopyrequestdatapracticeareaUpdate, TasktemplatelistcopyrequestdatapracticeareaDb

def convert_sdk_to_tasktemplatelistcopyrequestdatapracticeareaout(sdk_obj):
    # TODO
    return TasktemplatelistcopyrequestdatapracticeareaOut()

def convert_tasktemplatelistcopyrequestdatapracticeareain_to_sdk(model):
    # TODO
    return None
