# Adapter stubs for Activitydescriptioncreaterequestdatagroupsinner
from schemas.from_spec.activitydescriptioncreaterequestdatagroupsinner import ActivitydescriptioncreaterequestdatagroupsinnerIn, ActivitydescriptioncreaterequestdatagroupsinnerOut, ActivitydescriptioncreaterequestdatagroupsinnerUpdate, ActivitydescriptioncreaterequestdatagroupsinnerDb

def convert_sdk_to_activitydescriptioncreaterequestdatagroupsinnerout(sdk_obj):
    # TODO
    return ActivitydescriptioncreaterequestdatagroupsinnerOut()

def convert_activitydescriptioncreaterequestdatagroupsinnerin_to_sdk(model):
    # TODO
    return None
