# Adapter stubs for Calendarentrycreaterequestdataexternalpropertiesinner
from schemas.from_spec.calendarentrycreaterequestdataexternalpropertiesinner import CalendarentrycreaterequestdataexternalpropertiesinnerIn, CalendarentrycreaterequestdataexternalpropertiesinnerOut, CalendarentrycreaterequestdataexternalpropertiesinnerUpdate, CalendarentrycreaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_calendarentrycreaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return CalendarentrycreaterequestdataexternalpropertiesinnerOut()

def convert_calendarentrycreaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
