# Adapter stubs for Communicationupdaterequestdataexternalpropertiesinner
from schemas.from_spec.communicationupdaterequestdataexternalpropertiesinner import CommunicationupdaterequestdataexternalpropertiesinnerIn, CommunicationupdaterequestdataexternalpropertiesinnerOut, CommunicationupdaterequestdataexternalpropertiesinnerUpdate, CommunicationupdaterequestdataexternalpropertiesinnerDb

def convert_sdk_to_communicationupdaterequestdataexternalpropertiesinnerout(sdk_obj):
    # TODO
    return CommunicationupdaterequestdataexternalpropertiesinnerOut()

def convert_communicationupdaterequestdataexternalpropertiesinnerin_to_sdk(model):
    # TODO
    return None
