# Adapter stubs for Medicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinner
from schemas.from_spec.medicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinner import MedicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerIn, MedicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerOut, MedicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerUpdate, MedicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerDb

def convert_sdk_to_medicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerout(sdk_obj):
    # TODO
    return MedicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerOut()

def convert_medicalrecordsrequestcreaterequestdatamedicalbillsinnerpayersinnerin_to_sdk(model):
    # TODO
    return None
