# Adapter stubs for Documentautomationcreaterequestdatadocumenttemplate
from schemas.from_spec.documentautomationcreaterequestdatadocumenttemplate import DocumentautomationcreaterequestdatadocumenttemplateIn, DocumentautomationcreaterequestdatadocumenttemplateOut, DocumentautomationcreaterequestdatadocumenttemplateUpdate, DocumentautomationcreaterequestdatadocumenttemplateDb

def convert_sdk_to_documentautomationcreaterequestdatadocumenttemplateout(sdk_obj):
    # TODO
    return DocumentautomationcreaterequestdatadocumenttemplateOut()

def convert_documentautomationcreaterequestdatadocumenttemplatein_to_sdk(model):
    # TODO
    return None
