# Adapter stubs for Contactupdaterequestdatacustomfieldsetassociationsinnercustomfieldset
from schemas.from_spec.contactupdaterequestdatacustomfieldsetassociationsinnercustomfieldset import \
    ContactupdaterequestdatacustomfieldsetassociationsinnercustomfieldsetOut


def convert_sdk_to_contactupdaterequestdatacustomfieldsetassociationsinnercustomfieldsetout(sdk_obj):
    # TODO
    return ContactupdaterequestdatacustomfieldsetassociationsinnercustomfieldsetOut()

def convert_contactupdaterequestdatacustomfieldsetassociationsinnercustomfieldsetin_to_sdk(model):
    # TODO
    return None
