# Adapter stubs for Contactupdaterequestdatainstantmessengersinner
from schemas.from_spec.contactupdaterequestdatainstantmessengersinner import ContactupdaterequestdatainstantmessengersinnerIn, ContactupdaterequestdatainstantmessengersinnerOut, ContactupdaterequestdatainstantmessengersinnerUpdate, ContactupdaterequestdatainstantmessengersinnerDb

def convert_sdk_to_contactupdaterequestdatainstantmessengersinnerout(sdk_obj):
    # TODO
    return ContactupdaterequestdatainstantmessengersinnerOut()

def convert_contactupdaterequestdatainstantmessengersinnerin_to_sdk(model):
    # TODO
    return None
