# Adapter stubs for Calendarentrycreaterequestdatacalendarentryeventtype
from schemas.from_spec.calendarentrycreaterequestdatacalendarentryeventtype import CalendarentrycreaterequestdatacalendarentryeventtypeIn, CalendarentrycreaterequestdatacalendarentryeventtypeOut, CalendarentrycreaterequestdatacalendarentryeventtypeUpdate, CalendarentrycreaterequestdatacalendarentryeventtypeDb

def convert_sdk_to_calendarentrycreaterequestdatacalendarentryeventtypeout(sdk_obj):
    # TODO
    return CalendarentrycreaterequestdatacalendarentryeventtypeOut()

def convert_calendarentrycreaterequestdatacalendarentryeventtypein_to_sdk(model):
    # TODO
    return None
