# Adapter stubs for Activitydescriptionupdaterequestdatagroupsinner
from schemas.from_spec.activitydescriptionupdaterequestdatagroupsinner import ActivitydescriptionupdaterequestdatagroupsinnerIn, ActivitydescriptionupdaterequestdatagroupsinnerOut, ActivitydescriptionupdaterequestdatagroupsinnerUpdate, ActivitydescriptionupdaterequestdatagroupsinnerDb

def convert_sdk_to_activitydescriptionupdaterequestdatagroupsinnerout(sdk_obj):
    # TODO
    return ActivitydescriptionupdaterequestdatagroupsinnerOut()

def convert_activitydescriptionupdaterequestdatagroupsinnerin_to_sdk(model):
    # TODO
    return None
